export const chest = [
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "uncommon",
    "rare",
    "rare",
    "rare",
    "rare",
    "rare",
    "rare",
    "rare",
    "rare",
    "rare",
    "rare",
    "rare",
    "rare",
    "rare",
    "epic",
    "epic",
    "epic",
    "epic",
    "epic",
    "epic",
    "epic",
    "epic",
    "legendary",
    "legendary",
    "legendary",
    "legendary",
    "legendary",
    "import",
    "import",
    "import",
    "dark_shop"
    /* Także:
    ** common - 50% szans
    ** uncommon - 20% szans
    ** rare - 13%
    ** epic - 8%
    ** legedary - 5%
    ** import - 3%
    ** dark shop - 1%
    */
]

export const classes = [
    "limited",
    "common", //22
    "uncommon", //20
    "rare", //18
    "epic", //16
    "legendary", //14
    "import", //12
    "dark_shop", //10
]